# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.5.1
language: Swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xcodebuild -scheme SwiftExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test
- xcodebuild test -enableCodeCoverage YES -workspace Example/AppUpdate.xcworkspace -scheme AppUpdate-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=12.5' ONLY_ACTIVE_ARCH=NO | xcpretty
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/AppUpdate.xcworkspace -scheme AppUpdate-Example -sdk iphonesimulator14.5 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
